apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-nodejs-app
  template:
    metadata:
      labels:
        app: simple-nodejs-app
    spec:
      containers:
      - name: simple-nodejs-app
        image: northamerica-northeast1-docker.pkg.dev/llyods/{{.Values.image.name}}:{{.Values.image.tag}}
        ports:
        - containerPort: 3000
